// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHr909qaNQUoMxB_-JKh0YxXJkvFwj69o',
    appId: '1:372737542189:web:41c749a8af9e5f002410a4',
    messagingSenderId: '372737542189',
    projectId: 'sign-language-interprete-92453',
    authDomain: 'sign-language-interprete-92453.firebaseapp.com',
    storageBucket: 'sign-language-interprete-92453.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Bc0eHA0RC1DeI-x5sTP8E52KNgR2SAw',
    appId: '1:372737542189:android:d4753e9d40d8152e2410a4',
    messagingSenderId: '372737542189',
    projectId: 'sign-language-interprete-92453',
    storageBucket: 'sign-language-interprete-92453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtkK6i5ZEnB2xHdvdUXLwB5jVx_EU-pzM',
    appId: '1:372737542189:ios:e85896a86e2cf3a02410a4',
    messagingSenderId: '372737542189',
    projectId: 'sign-language-interprete-92453',
    storageBucket: 'sign-language-interprete-92453.firebasestorage.app',
    iosBundleId: 'com.example.boilerplateFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtkK6i5ZEnB2xHdvdUXLwB5jVx_EU-pzM',
    appId: '1:372737542189:ios:e85896a86e2cf3a02410a4',
    messagingSenderId: '372737542189',
    projectId: 'sign-language-interprete-92453',
    storageBucket: 'sign-language-interprete-92453.firebasestorage.app',
    iosBundleId: 'com.example.boilerplateFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHr909qaNQUoMxB_-JKh0YxXJkvFwj69o',
    appId: '1:372737542189:web:3e335f3eb70232242410a4',
    messagingSenderId: '372737542189',
    projectId: 'sign-language-interprete-92453',
    authDomain: 'sign-language-interprete-92453.firebaseapp.com',
    storageBucket: 'sign-language-interprete-92453.firebasestorage.app',
  );
}
